version: '3.8'

services:
  app:
    build: .
    container_name: graduation_work_app
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: graduation_work_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graduation_work_development
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
